[package]
authors = ["laggui <lagrange.guillaume.1@gmail.com>"]
edition.workspace = true
license.workspace = true
name = "custom-image-dataset"
description = "Example implementation for loading a custom image dataset from disk"
publish = false
version.workspace = true

[lints]
workspace = true

[features]
default = ["deepcode/std", "deepcode/tui"]
tch-gpu = ["deepcode/tch"]
wgpu = ["deepcode/wgpu", "deepcode/fusion"]
metal = ["deepcode/metal", "deepcode/fusion"]

[dependencies]
# Disable autotune default for now (convolutions not optimized)
deepcode = { path = "../../crates/deepcode", features = [
    "train",
    "vision",
    "network",
], default-features = false }


# File download
flate2 = { workspace = true }
tar = "0.4.44"
