[package]
authors = ["Md. Sulaiman <dev.sulaiman@icloud.com>"]
edition.workspace = true
license.workspace = true
name = "custom-wgpu-kernel"
publish = false
version.workspace = true

[lints]
workspace = true

[dependencies]
deepcode = { path = "../../crates/deepcode", default-features = false, features = [
    "autodiff",
    "wgpu",
    "autotune",
    "template",
] }
deepcl = { workspace = true, features = ["wgpu"] }

# Serialization
log = { workspace = true }
serde = { workspace = true, features = ["std", "derive"] }

# Wgpu internal dependencies
derive-new = { workspace = true }
bytemuck = { workspace = true }
