[package]
authors = []
edition.workspace = true
license.workspace = true
name = "device_sharing"
publish = false
version.workspace = true

[features]
cuda = ["deepcl/cuda"]
default = []
wgpu = ["deepcl/wgpu"]

[dependencies]
deepcl = { path = "../../crates/deepcl", version = "0.7.0" }
half = { workspace = true }

sum_things = { path = "../sum_things" }
wgpu = { version = "26.0.0", features = ["fragile-send-sync-non-atomic-wasm"] }
