[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "Backend router decorator over the network."
edition.workspace = true
keywords = ["deep-learning", "machine-learning", "data"]
license.workspace = true
name = "deepcode-remote"
readme.workspace = true
repository = "https://github.com/kothagpt/deepcode/tree/main/crates/deepcode-router-remote"
documentation = "https://docs.rs/deepcode-router-remote"
version.workspace = true

[lints]
workspace = true

[features]
default = ["client", "server"]
doc = []
client = ["tokio-tungstenite", "async-channel", "tokio/sync"]
server = [
    "tokio-tungstenite",
    "async-channel",
    "tokio/sync",
    "axum",
    "tracing-core",
    "tracing-subscriber",
]


[dependencies]
deepcode-ir = { path = "../deepcode-ir", version = "0.1.0", default-features = true }
deepcode-tensor = { path = "../deepcode-tensor", version = "0.1.0", default-features = true }
deepcode-common = { path = "../deepcode-common", version = "0.1.0", default-features = true }
deepcode-router = { path = "../deepcode-router", version = "0.1.0", default-features = true }
deepcode-communication = { path = "../deepcode-communication", version = "0.1.0", features = [
    "data-service",
    "websocket",
] }

bytes = { workspace = true }

# Basic dependencies
derive-new = { workspace = true }
log = { workspace = true }

# Shared dependencies
tokio = { workspace = true, features = ["rt-multi-thread"] }
serde = { workspace = true, features = ["derive"] }
serde_bytes = { workspace = true }
rmp-serde = { workspace = true }
futures-util = { workspace = true }

# Client dependencies
async-channel = { workspace = true, optional = true }
tokio-tungstenite = { workspace = true, optional = true }

# Server dependencies
axum = { workspace = true, features = ["ws"], optional = true }
tracing-core = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }
tokio-util = { workspace = true }

[dev-dependencies]
deepcode-ndarray = { path = "../deepcode-ndarray", version = "0.1.0" }

[package.metadata.docs.rs]
features = ["doc"]
rustdoc-args = ["--cfg", "docsrs"]
