[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
edition.workspace = true
license.workspace = true
name = "text-classification"
publish = false
version.workspace = true

[lints]
workspace = true

[features]
default = []
f16 = []
flex32 = []
ndarray = ["deepcode/ndarray"]
ndarray-blas-accelerate = ["deepcode/ndarray", "deepcode/accelerate"]
ndarray-blas-netlib = ["deepcode/ndarray", "deepcode/blas-netlib"]
ndarray-blas-openblas = ["deepcode/ndarray", "deepcode/openblas"]
tch-cpu = ["deepcode/tch"]
tch-gpu = ["deepcode/tch"]
wgpu = ["deepcode/wgpu"]
vulkan = ["deepcode/vulkan"]
remote = ["deepcode/remote"]
cuda = ["deepcode/cuda"]
rocm = ["deepcode/rocm"]
metal = ["deepcode/metal"]
ddp = ["deepcode/collective"]

[dependencies]
# Deepcode
deepcode = { path = "../../crates/deepcode", features = [
    "train",
    "tui",
    "sqlite-bundled",
    "metrics",
    "ndarray",
    "autotune",
    "fusion",
    "std",
], default-features = false }

# Tokenizer
tokenizers = { version = "0.22.1", default-features = false, features = [
    "onig",
    "http",
] }

# Utils
derive-new = { workspace = true }
serde = { workspace = true, features = ["std", "derive"] }
