[package]
authors = ["Md. Sulaiman <dev.sulaiman@icloud.com>"]
edition.workspace = true
license.workspace = true
name = "guide"
publish = false
version.workspace = true

[lints]
workspace = true

[features]
default = ["deepcode/std", "deepcode/tui", "deepcode/fusion"]

[dependencies]
# Disable autotune default for convolutions
deepcode = { path = "../../crates/deepcode", features = [
    "webgpu",
    "train",
    "vision",
], default-features = false }

# Serialization
log = { workspace = true }
serde = { workspace = true, features = ["std", "derive"] }
