[package]
name = "deepcode-collective-multinode-tests"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["ndarray"]
ndarray = ["deepcode/ndarray"]

[dependencies]
deepcode = { path = "../../deepcode", default-features = false, features = ["std"] }
deepcode-common = { path = "../../deepcode-common", default-features = false }
deepcode-collective = { path = "..", features = ["orchestrator"] }
deepcode-communication = { path = "../../deepcode-communication" }

tokio = { workspace = true, features = ["rt-multi-thread", "process"] }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
interprocess = "2.2.3"
rmp-serde = { workspace = true }
tokio-util = { workspace = true, features = ["codec"] }
tokio-serde = { version = "0.9.0", features = ["messagepack"] }
futures = { workspace = true }


[[bin]]
name = "global"
path = "src/bin/global.rs"

[[bin]]
name = "node"
path = "src/bin/node.rs"
