[package]
authors = ["Md. Sulaiman <dev.sulaiman@icloud.com>"]
edition.workspace = true
license.workspace = true
name = "multi-gpus"
publish = false
version.workspace = true

[lints]
workspace = true

[features]
default = []
f16 = []
flex32 = []
tch-gpu = ["deepcode/tch"]
cuda = ["deepcode/cuda"]
rocm = ["deepcode/rocm"]

[dependencies]
# Deepcode
deepcode = { path = "../../crates/deepcode", features = [
    "autotune",
    "fusion",
    "collective",
    "train",
    "std",
], default-features = false }
text-classification = { path = "../text-classification" }
