[package]
authors = ["Dilshod Tadjibaev (@antimora)"]
edition.workspace = true
license = "MIT OR Apache-2.0"
name = "import-model-weights"
publish = false
version = "0.1.0"

[lints]
workspace = true

[dependencies]

deepcode = { path = "../../crates/deepcode", features = [
    "ndarray",
    "dataset",
    "vision",
] }

deepcode-import = { path = "../../crates/deepcode-import", features = [
    "pytorch",
    "safetensors",
], default-features = false }
