[book]
authors = [
    "Wouter Doppenberg",
    "Nathaniel Simard",
    "Louis Fortier-Dubois",
    "Dilshod Tadjibaev",
    "Guillaume Lagrange",
    "Sylvain Benner",
    "Bjorn Beishline"
]
language = "en"
multilingual = false
src = "src"
title = "The Deepcode Book 🔥"

[output.html]
mathjax-support = true
