[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
edition.workspace = true
license.workspace = true
name = "custom-deepcl-kernel"
publish = false
version.workspace = true

[lints]
workspace = true

[dependencies]
deepcode = { path = "../../crates/deepcode", default-features = false, features = [
    "autodiff",
    "wgpu",
    "autotune",
    "template",
] }
deepcl = { path = "../../deepcl/crates/deepcl", default-features = false, features = ["wgpu"] }

# Serialization
log = { workspace = true }
serde = { workspace = true, features = ["std", "derive"] }

# Wgpu internal dependencies
bytemuck = { workspace = true }
derive-new = { workspace = true }
