[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
edition.workspace = true
license.workspace = true
name = "mnist"
publish = false
version.workspace = true

[lints]
workspace = true

[features]
default = ["deepcode/tui"]
ndarray = ["deepcode/ndarray"]
ndarray-blas-accelerate = ["deepcode/ndarray", "deepcode/accelerate"]
ndarray-blas-netlib = ["deepcode/ndarray", "deepcode/blas-netlib"]
ndarray-blas-openblas = ["deepcode/ndarray", "deepcode/openblas"]
tch-cpu = ["deepcode/tch"]
tch-gpu = ["deepcode/tch"]
remote = ["deepcode/remote"]
wgpu = ["deepcode/wgpu", "deepcode/default"]
metal = ["deepcode/metal", "deepcode/default"]
cuda = ["deepcode/cuda", "deepcode/default"]
vulkan = ["deepcode/vulkan", "deepcode/default"]
rocm = ["deepcode/rocm", "deepcode/default"]

[dependencies]
# Disable autotune default for now (convolutions not optimized)
deepcode = { path = "../../crates/deepcode", features = [
    "train",
    "vision",
    "metrics",
    "std",
    "fusion",
    "ndarray",
    "autotune",
], default-features = false }

# Serialization
log = { workspace = true }
rand.workspace = true
serde = { workspace = true, features = ["std", "derive"] }
